import Header from "../components/Header";
import Image from "next/image";
import Head from "next/head";
import styled from "styled-components";
import Navigation from "../components/Navigation";
import Link from "next/link";

export default function Competitions() {
  return (
    <StyledDiv>
      <Head>
        <title>MatchBall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src={"/playergroup.jpg"}
        alt={"Player group background image"}
        fill={true}
        objectFit={"cover"}
        objectPosition={"center"}
        style={{ position: "absolute", zIndex: -1 }}
      />
      <Header teaser={"plan your tournament... or go with the flow"} />
      <main>
        <nav>
          <Link href={"/plan"}>Plan ahead</Link>
          <Link href={"/games"}>Go with the flow</Link>
        </nav>
      </main>
      <Navigation />
    </StyledDiv>
  );
}

const StyledDiv = styled.div`
  height: 100dvh;
  width: 100dvw;
  padding: 0;
  font-size: 20px;
  font-family: baloo_2;
  position: relative;
  overflow: hidden;
`;
