import getAllTeams from "../utils/getAllTeams";
import { useEffect, useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import { Team } from "../interfaces/interfaces";
import TeamComponent from "../components/TeamComponent";
import styled from "styled-components";
import Image from "next/image";
import ArrowNavigation from "../components/arrowNavigation";

export default function TeamChoiceForm(): JSX.Element {
  const [teams, setTeams] = useState<[Team]>([
    { players: [], points: 0, id: "" },
  ]);

  useEffect(() => {
    async function fetchTeamsAndUpdateTeamState() {
      const fetchedTeams = await getAllTeams();
      setTeams(fetchedTeams);
    }
    fetchTeamsAndUpdateTeamState();
  }, []);

  return (
    <StyledDiv>
      <Head>
        <title>MatchBall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src={"/playergroup.jpg"}
        alt={"Player group background image"}
        fill={true}
        objectFit={"cover"}
        objectPosition={"center"}
        style={{ position: "absolute", zIndex: -1 }}
      />
      <Header teaser={"Teams"} />
      <section>
        <StyledUl data-cy="team-list">
          {teams.map((team) => {
            return (
              <li key={team.id}>
                <TeamComponent team={team} isClickable={true} />
              </li>
            );
          })}
        </StyledUl>
      </section>
      <ArrowNavigation
        hrefBackward="/games"
        hrefForward="/scoreForm"
        hrefPlus="/teamChoiceForm"
        displayPlus={true}
      />
    </StyledDiv>
  );
}
const StyledUl = styled.ul`
  list-style-type: none;
  display: flex;
  flex-direction: column;
  gap: 1rem;
  overflow-y: scroll;
  height: 70vh;
  width: 100vw;
`;

const StyledDiv = styled.div`
  height: 100dvh;
  width: 100dvw;
  padding: 0;
  font-size: 20px;
  font-family: baloo_2;
  overflow: hidden;
`;
